### ISSUE TITLE
Problème de déploiement : erreur de fichier

### ISSUE THREAD

**Issue by damienbelliard** [OCSInventory-NG/Agent-Deployment-Tool#1]
Problème lors du déploiement via l'outil Agent-Deployment-Tool 
Le fichier de log ne semble pas être accessible. 
![image001](https://cloud.githubusercontent.com/assets/12798317/10023991/48f40016-6155-11e5-954a-b4d42b0af2c3.png)

**Comment by gillesdubois** [comment]
Ce problème viendrai du fait que la tool de déploiement ne gère pas les repertoires 64 bits de windows => ProgramsFiles(X86) et ProgamsFiles
Du coup l'agent de déploiement se perd et ne sait plus quoi faire.
Voila pourquoi il ne peux pas lire ou ouvrir le fichier ... car il ne comprend pas l'arbo windows 64Bits

Je vais voir pour un Fix !
