### ISSUE TITLE
Unable to access Registry on remote host

### ISSUE THREAD

**Issue by florianpunz** [OCSInventory-NG/Agent-Deployment-Tool#10]
Hello,
i tried deploying OCS using the Tool on multiple devices after successfully doing it on a test computer. On the test device everything works fine, although its giving me an ERROR for a log file, it still shows up on the dashboard, seems like everything works as intended.

Im currently using the (to date) latest versions of the software i downloaded today through the email i got.
DEPLOY TOOL (ver 2.3)
Win Agent (ver 2.10.1.0)
Win Packager (ver 2.8)

Successful deployment:
--------------------------------------------------------------------------------------------------------------------------------------
Host <192.168.XXX.XX> Testing connection to remote host...
Host <192.168.XXX.XX> Trying to connect to remote host...
Host <192.168.XXX.XX> Trying to get remote "Program Files" and "ProgramData" directories using Registry...
Host <192.168.XXX.XX> Using directory <C:\Program Files (x86)> for Program Files and <C:\ProgramData\OCS Inventory NG\Agent> for Program Data on remote host...
Host <192.168.XXX.XX> Creating setup directory on remote host...
Host <192.168.XXX.XX> Copying files on remote host on directory <\\192.168.XXX.XX\C$\ProgramData\OCS Inventory NG\Agent>...
Host <192.168.XXX.XX> Launching Agent Setup on remote host...
Host <192.168.XXX.XX> Retrieving Setup Log file for remote host...
Host <192.168.XXX.XX> *** ERROR *** Unable to open or read setup log file on remote host:  Das System kann die angegebene Datei nicht finden.

Host <192.168.XXX.XX> Disconnecting from remote host...
 
Deployment finished (0 success, 1 failed) !
--------------------------------------------------------------------------------------------------------------------------------------

The following errors are from the first time trying to deploy on the rest of the devices that are online:
--------------------------------------------------------------------------------------------------------------------------------------
Host <192.168.XXX.XX> Trying to get remote "Program Files" and "ProgramData" directories using Registry...
Host <192.168.XXX.XX> *** Warning *** Unable to access Registry on remote host:  Zugriff verweigert

Host <192.168.XXX.XX> *** Warning *** Unable to access Registry on remote host:  Das Handle ist ung ltig.

Host <192.168.XXX.XX> Trying to get remote"Program Files" directory using PsExec...
--------------------------------------------------------------------------------------------------------------------------------------

Also i didnt change anything from the test system... and it also works fine uninstalling and redeploying on the test system.
The credentials i put in the packager are also 100% working

Thanks for any input.

**Comment by Neustradamus** [comment]
@florianpunz: Why have you closed your ticket?
It has been solved?
