### ISSUE TITLE
Plugins are always copied in "Program Files", even if the agent setup directory is changed

### ISSUE THREAD

**Issue by ghost** [OCSInventory-NG/Agent-Deployment-Tool#3]
With the version 2.1.0.2, if you change the agent setup directory, the instalation is done in the correct place but the plugins are always copied to "Program Files\OCS Inventory Agent\Plugins". This happens with Windows XP, Windows 2003, Windows 2008 and Windows 2012 clients.

In my case, I need to have a standard path for setup and plugins as well (i.e c:\OCSInventoryAgent).

**Comment by gehasia** [comment]
This should be resolved with this fix (is someone is willing to pull it !)

https://github.com/OCSInventory-NG/Agent-Deployment-Tool/pull/4
